package edu.ncsu.lubick.localHub.database;

public class DBAbstractionException extends RuntimeException {

	private static final long serialVersionUID = -8535679870475223528L;

	// All of the constructors are autogenerated from the superclass
	public DBAbstractionException()
	{
		super();
	}

	public DBAbstractionException(String message, Throwable cause,
			boolean enableSuppression, boolean writableStackTrace)
	{
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public DBAbstractionException(String message, Throwable cause)
	{
		super(message, cause);
	}

	public DBAbstractionException(Throwable cause)
	{
		super(cause);

	}

	public DBAbstractionException(String message)
	{
		super(message);
	}

}
