package org.lubick.unitTests;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.lubick.localHub.ToolStream;
import org.lubick.localHub.forTesting.IdealizedToolStream;
import org.lubick.localHub.forTesting.IdealizedToolStream.ToolUsage;
import org.lubick.localHub.forTesting.TestUtilities;

public class TestToolStream {

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void testManualCreationOfToolStream() {
		
		Date firstDate = TestUtilities.truncateTimeToMinute(new Date());
		
		IdealizedToolStream iToolStream = new IdealizedToolStream(firstDate);
		
		
		Date secondDate = new Date(firstDate.getTime()+1000);
		
		iToolStream.addToolUsage("ToolString", "ClassString", "Keypresses",firstDate, 2);
		iToolStream.addToolUsage("WhomboTool #5", "Debug", "Ctrl+5",secondDate, 1);
		
		
		//I'm scoping this out to avoid copy+paste problems with these assertions
		{
			List<IdealizedToolStream.ToolUsage> tools = iToolStream.getAsList();
	
			assertEquals("ToolString", tools.get(0).getToolName());
			assertEquals("ClassString", tools.get(0).getToolClass());
			assertEquals("Keypresses", tools.get(0).getToolKeyPresses());
			assertEquals(firstDate, tools.get(0).getTimeStamp());
			assertEquals(2, tools.get(0).getDuration());
			
			assertEquals("WhomboTool #5", tools.get(1).getToolName());
			assertEquals("Debug", tools.get(1).getToolClass());
			assertEquals("Ctrl+5", tools.get(1).getToolKeyPresses());
			assertEquals(secondDate, tools.get(1).getTimeStamp());
			assertEquals(1, tools.get(1).getDuration());
		}
		
		ToolStream convertedToolStream = ToolStream.generateFromJSON(iToolStream.toJSON());
		
		assertTrue(iToolStream.isEquivalent(convertedToolStream));
		
		{
			List<ToolStream.ToolUsage> tools = convertedToolStream.getAsList();
		
			assertEquals("ToolString", tools.get(0).getToolName());
			assertEquals("ClassString", tools.get(0).getToolClass());
			assertEquals("Keypresses", tools.get(0).getToolKeyPresses());
			assertEquals(firstDate, tools.get(0).getTimeStamp());
			assertEquals(2, tools.get(0).getDuration());
			
			assertEquals("WhomboTool #5", tools.get(1).getToolName());
			assertEquals("Debug", tools.get(1).getToolClass());
			assertEquals("Ctrl+5", tools.get(1).getToolKeyPresses());
			assertEquals(secondDate, tools.get(1).getTimeStamp());
			assertEquals(1, tools.get(1).getDuration());
		}
		
	}

	
	@Test
	public void testAutomaticallyCreatedToolStreams() throws Exception 
	{
		IdealizedToolStream iToolStream = IdealizedToolStream.generateRandomToolStream(10);
		List<ToolUsage> iTools = iToolStream.getAsList();
		
		assertEquals(10, iTools.size());
		assertEquals(10, iToolStream.numberOfToolUses());
		
		GregorianCalendar gc = new GregorianCalendar();
		
		//I want the autogenerated tool to have every tool's timestamp be within the same minute,
		//but, all of the seconds should not be the same.  As long as one of them is different,
		//that will be a valid test
		int firstSeconds = -1;
		boolean areAllSecondsTheSameHuh = true;
		int allMinutes = -1;
		
		for(ToolUsage tu : iTools)
		{
			assertNotNull(tu.getTimeStamp());
			assertNotNull(tu.getToolClass());
			assertNotNull(tu.getToolKeyPresses());
			assertNotNull(tu.getToolName());
			assertNotEquals(tu.getDuration(),0);
			
			//Tests to make sure that the 
			gc.setTime(tu.getTimeStamp());
			
			if (firstSeconds == -1)
			{
				firstSeconds = gc.get(GregorianCalendar.SECOND);
			}
			else {
				areAllSecondsTheSameHuh = areAllSecondsTheSameHuh && firstSeconds == gc.get(GregorianCalendar.SECOND);
			}
			
			if (allMinutes == -1)
			{
				allMinutes = gc.get(GregorianCalendar.MINUTE);
			}
			else
			{
				assertEquals(allMinutes, gc.get(GregorianCalendar.MINUTE));
			}
			
		}
		
		assertFalse(areAllSecondsTheSameHuh);
		
		ToolStream convertedToolStream = ToolStream.generateFromJSON(iToolStream.toJSON());
		
		List<org.lubick.localHub.ToolStream.ToolUsage> theRealTools = convertedToolStream.getAsList();
		
		assertEquals(iTools.size(), theRealTools.size());
		assertEquals(iToolStream.numberOfToolUses(), theRealTools.size());
		
		assertTrue(iToolStream.isEquivalent(convertedToolStream));
	}
}
